# Generated by Django 5.1.4 on 2025-09-07 01:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(blank=True, related_name='support_inapp_inbox', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_inapp_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'In-App Message',
                'verbose_name_plural': 'In-App Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('inapp', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='inapp', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients'), ('marketers', 'Marketers')], default='clients', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('send_time', models.TimeField(blank=True, help_text='Optional daily send time (local)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('inapp', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='inapp', max_length=10)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients'), ('marketers', 'Marketers')], default='clients', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('recipients_sample', models.JSONField(blank=True, default=list, help_text='Small sample for preview')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_outbounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Outbound Message',
                'verbose_name_plural': 'Outbound Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('daily', models.BooleanField(default=False)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('one_shot_at', models.DateTimeField(blank=True, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_triggers', to='adminSupport.messagetemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Trigger',
                'verbose_name_plural': 'Scheduled Triggers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_started_conversations', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='support_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Conversation',
                'verbose_name_plural': 'Support Conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_system', models.BooleanField(default=False)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Attachment metadata list')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='adminSupport.supportconversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='adminSupport.supportmessage')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': 'Support Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='adminSupport.supportmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support Message Receipt',
                'verbose_name_plural': 'Support Message Receipts',
            },
        ),
        migrations.CreateModel(
            name='InboxEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='adminSupport.inappmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_inbox_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inbox Entry',
                'verbose_name_plural': 'Inbox Entries',
                'ordering': ['-message__created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'message'), name='unique_inbox_user_message')],
            },
        ),
        migrations.AddIndex(
            model_name='messagetemplate',
            index=models.Index(fields=['is_active', 'channel'], name='adminSuppor_is_acti_7b302d_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessagereceipt',
            constraint=models.UniqueConstraint(fields=('message', 'user'), name='unique_message_user_receipt'),
        ),
    ]
