# Generated by Django 5.1.4 on 2025-09-07 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingSettings',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('auto_birthday', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Messaging Settings',
                'verbose_name_plural': 'Messaging Settings',
            },
        ),
        migrations.CreateModel(
            name='BirthdayTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=180)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('inapp', 'In-App')], default='sms', max_length=16)),
                ('audience', models.CharField(default='clients', help_text='Audience (clients/marketers/all)', max_length=80)),
                ('message', models.TextField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
