# Generated by Django 5.1.4 on 2025-09-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0003_autobirthdaysetting_birthdaytemplate_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoBirthdaySetting',
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='auto_special_day',
            field=models.BooleanField(default=True),
        ),
    ]
