# Generated by Django 5.1.4 on 2025-09-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0004_delete_autobirthdaysetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaytemplate',
            name='template_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('special', 'Special Day')], default='birthday', help_text='Whether this template is a birthday template or a special-day template', max_length=20),
        ),
    ]
