# Generated by Django 5.1.4 on 2025-09-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0005_birthdaytemplate_template_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoSpecialSetting',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Special Day Setting',
                'verbose_name_plural': 'Auto Special Day Settings',
            },
        ),
        migrations.AlterField(
            model_name='birthdaytemplate',
            name='template_type',
            field=models.CharField(choices=[('birthday', 'Birthday'), ('special', 'Special Day')], default='birthday', max_length=20),
        ),
    ]
