# Generated by Django 5.1.4 on 2025-09-07 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0006_autospecialsetting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional internal name', max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField(help_text='HTML body (editor output)')),
                ('plain_body', models.TextField(blank=True, help_text='Plain-text alternative (auto-generated if blank)', null=True)),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('clients', 'Clients'), ('marketers', 'Marketers')], db_index=True, default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('recipients_sample', models.JSONField(blank=True, default=list)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Newsletter Campaign',
                'verbose_name_plural': 'Newsletter Campaigns',
                'ordering': ['-created_at'],
            },
        ),
    ]
