# Generated by Django 5.1.4 on 2025-09-08 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0007_newslettercampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='birthday_channel',
            field=models.CharField(choices=[('inapp', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=16),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='birthday_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adminSupport.birthdaytemplate'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='birthday_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='newsletter_batch_size',
            field=models.PositiveIntegerField(default=50, help_text='Batch size when sending newsletters'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='newsletter_from_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='newsletter_use_celery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='special_channel',
            field=models.CharField(choices=[('inapp', 'In-App'), ('sms', 'SMS'), ('email', 'Email')], default='email', max_length=16),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='special_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='adminSupport.birthdaytemplate'),
        ),
        migrations.AddField(
            model_name='messagingsettings',
            name='special_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
