# Generated by Django 5.1.4 on 2025-10-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0010_staffroster'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffroster',
            new_name='adminSuppor_active_ab8c31_idx',
            old_name='staffroster_active_idx',
        ),
    ]
