# Generated by Django 5.1.4 on 2025-10-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0012_staffmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=50),
        ),
    ]
