# Generated by Django 5.1.4 on 2025-11-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0014_customspecialday'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagingsettings',
            name='birthday_days_advance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
