# Generated by Django 5.1.4 on 2025-11-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0015_messagingsettings_birthday_days_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='message_type',
            field=models.CharField(db_index=True, default='generic', help_text='Categorizes the automation source (e.g., birthday, special_day, newsletter)', max_length=30),
        ),
    ]
