# Generated by Django 5.1.4 on 2025-11-11 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSupport', '0016_outboundmessage_message_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetheme',
            name='theme_type',
            field=models.CharField(choices=[('default', 'Default'), ('holiday', 'Holiday'), ('seasonal', 'Seasonal'), ('campaign', 'Campaign'), ('special', 'Special Highlight')], default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='StaffBroadcast',
            fields=[
                ('repeat_schedule', models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='none', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('channels', models.JSONField(blank=True, default=list, help_text='List of channels e.g. ["email", "sms"]')),
                ('audience_type', models.CharField(choices=[('all_staff', 'All Staff'), ('individuals', 'Specific Individuals')], default='all_staff', max_length=30)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Broadcast',
                'verbose_name_plural': 'Staff Broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffBroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('inapp', 'In-App')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='adminSupport.staffbroadcast')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_deliveries', to='adminSupport.staffmember')),
            ],
            options={
                'verbose_name': 'Staff Broadcast Recipient',
                'verbose_name_plural': 'Staff Broadcast Recipients',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='adminSuppor_status_b063cb_idx'), models.Index(fields=['channel'], name='adminSuppor_channel_0c7ab6_idx')],
            },
        ),
    ]
