#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset

: "${FIREBASE_ANDROID_API_KEY:?Set FIREBASE_ANDROID_API_KEY}"
: "${FIREBASE_ANDROID_APP_ID:?Set FIREBASE_ANDROID_APP_ID}"
: "${FIREBASE_ANDROID_MESSAGING_SENDER_ID:?Set FIREBASE_ANDROID_MESSAGING_SENDER_ID}"
: "${FIREBASE_ANDROID_PROJECT_ID:?Set FIREBASE_ANDROID_PROJECT_ID}"
: "${FIREBASE_ANDROID_STORAGE_BUCKET:?Set FIREBASE_ANDROID_STORAGE_BUCKET}"

BUILD_TYPE=${1:-apk}
shift || true

pushd "$(dirname "$0")/../real_estate_app" > /dev/null
flutter clean
flutter pub get
flutter build "$BUILD_TYPE" --release \
  --dart-define=FIREBASE_ANDROID_API_KEY="$FIREBASE_ANDROID_API_KEY" \
  --dart-define=FIREBASE_ANDROID_APP_ID="$FIREBASE_ANDROID_APP_ID" \
  --dart-define=FIREBASE_ANDROID_MESSAGING_SENDER_ID="$FIREBASE_ANDROID_MESSAGING_SENDER_ID" \
  --dart-define=FIREBASE_ANDROID_PROJECT_ID="$FIREBASE_ANDROID_PROJECT_ID" \
  --dart-define=FIREBASE_ANDROID_STORAGE_BUCKET="$FIREBASE_ANDROID_STORAGE_BUCKET" \
  "$@"
popd > /dev/null
