# Generated by Django 5.1.4 on 2025-02-03 08:25

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('marketer', 'Marketer')], max_length=20, null=True, verbose_name='Role')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('date_registered', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Registered')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country of Residence')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('marketer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_users', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Marketer')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custom User',
                'verbose_name_plural': 'Custom Users',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Estate Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('estate_size', models.CharField(max_length=255, verbose_name='Estate Size')),
                ('title_deed', models.CharField(choices=[('FCDA RofO', 'FCDA RofO'), ('FCDA CofO', 'FCDA CofO'), ('AMAC', 'AMAC')], max_length=255, verbose_name='Title Deed')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added')),
            ],
            options={
                'verbose_name': 'Estate',
                'verbose_name_plural': 'Estates',
            },
        ),
        migrations.CreateModel(
            name='PlotNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Plot Number')),
            ],
            options={
                'verbose_name': 'Plot Number',
                'verbose_name_plural': 'Plot Numbers',
            },
        ),
        migrations.CreateModel(
            name='PlotSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True, verbose_name='Plot Size')),
            ],
            options={
                'verbose_name': 'Plot Size',
                'verbose_name_plural': 'Plot Sizes',
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin User',
                'verbose_name_plural': 'Admin Users',
            },
            bases=('estateApp.customuser',),
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client User',
                'verbose_name_plural': 'Client Users',
            },
            bases=('estateApp.customuser',),
        ),
        migrations.CreateModel(
            name='MarketerUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketer User',
                'verbose_name_plural': 'Marketer Users',
            },
            bases=('estateApp.customuser',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('complaint', 'Complaint'), ('enquiry', 'Enquiry'), ('compliment', 'Compliment')], max_length=20, verbose_name='Message Type')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Date Sent')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('reply', models.TextField(blank=True, null=True, verbose_name='Admin Reply')),
                ('date_replied', models.DateTimeField(blank=True, null=True, verbose_name='Date Replied')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'ordering': ['date_sent'],
            },
        ),
        migrations.CreateModel(
            name='EstatePlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField(default=0, verbose_name='Total Units')),
                ('available_units', models.PositiveIntegerField(default=0, verbose_name='Available Units')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_plots', to='estateApp.estate', verbose_name='Estate')),
                ('plot_numbers', models.ManyToManyField(related_name='estates', to='estateApp.plotnumber', verbose_name='Plot Numbers')),
                ('plot_sizes', models.ManyToManyField(to='estateApp.plotsize', verbose_name='Plot Sizes')),
            ],
            options={
                'verbose_name': 'Estate Plot',
                'verbose_name_plural': 'Estate Plots',
            },
        ),
        migrations.CreateModel(
            name='PlotAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('part', 'Part Payment')], max_length=10, verbose_name='Payment Type')),
                ('date_allocated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Allocated')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registered Client Name')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.estate', verbose_name='Estate Name')),
                ('plot_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estateApp.plotnumber', verbose_name='Plot Number')),
                ('plot_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.plotsize', verbose_name='Plot Size')),
            ],
            options={
                'verbose_name': 'Plot Allocation',
                'verbose_name_plural': 'Plot Allocations',
                'unique_together': {('estate', 'plot_number')},
            },
        ),
    ]
