# Generated by Django 5.1.4 on 2025-02-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
