# Generated by Django 5.1.4 on 2025-02-03 18:21

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0004_remove_customuser_username'),
    ]

    operations = [
        # Step 1: Create the through model first
        migrations.CreateModel(
            name='PlotSizeUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('available_units', models.PositiveIntegerField(default=0)),
                ('estate_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.estateplot')),
                ('plot_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.plotsize')),
            ],
        ),
        
        # Step 2: Remove old M2M field and add new one with through model
        migrations.RemoveField(
            model_name='estateplot',
            name='plot_sizes',
        ),
        migrations.AddField(
            model_name='estateplot',
            name='plot_sizes',
            field=models.ManyToManyField(through='estateApp.PlotSizeUnits', to='estateApp.plotsize'),
        ),
        
        # Other operations (keep unchanged)
        migrations.RemoveField(
            model_name='estateplot',
            name='available_units',
        ),
        migrations.RemoveField(
            model_name='estateplot',
            name='total_units',
        ),
        migrations.AlterField(
            model_name='estateplot',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_plots', to='estateApp.estate'),
        ),
        migrations.AlterField(
            model_name='estateplot',
            name='plot_numbers',
            field=models.ManyToManyField(related_name='estates', to='estateApp.plotnumber'),
        ),
    ]