# Generated by Django 5.1.4 on 2025-02-03 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0005_remove_estateplot_available_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotallocation',
            name='plot_size_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estateApp.plotsizeunits'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plotallocation',
            name='date_allocated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
