# Generated by Django 5.1.4 on 2025-02-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0006_plotallocation_plot_size_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotallocation',
            name='plot_size_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='estateApp.plotsizeunits'),
        ),
        migrations.AlterField(
            model_name='plotsizeunits',
            name='estate_plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plotsizeunits', to='estateApp.estateplot'),
        ),
    ]
