# Generated by Django 5.1.4 on 2025-02-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0007_alter_plotallocation_plot_size_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_size',
            field=models.FloatField(max_length=255, verbose_name='Estate Size'),
        ),
    ]
