# Generated by Django 5.1.4 on 2025-02-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0008_alter_estate_estate_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='estate_size',
            field=models.CharField(max_length=255, verbose_name='Estate Size'),
        ),
    ]
