# Generated by Django 5.1.4 on 2025-02-15 08:44

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0009_alter_estate_estate_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateAmenitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenities', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('gated_security', 'Gated Security'), ('surveillance', '24/7 Surveillance'), ('power_backup', 'Power Backup'), ('water_supply', 'Water Supply & Treatment'), ('clubhouse', 'Clubhouse/Community Center'), ('swimming_pool', 'Swimming Pool'), ('gym', 'Gym/Fitness Center'), ('sports_facilities', 'Sports Facilities'), ('playground', "Children's Playground"), ('school', 'School/Educational Facility'), ('clinic', 'Health Clinic'), ('retail', 'Retail/Commercial Area'), ('religious', 'Religious Facility'), ('green_areas', 'Green Areas & Parks'), ('parking', 'Parking Spaces'), ('management_office', 'Estate Management Office'), ('high_speed_internet', 'High-Speed Internet'), ('smart_home', 'Smart Home Systems')], max_length=210, null=True, verbose_name='Select Amenities')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_amenity', to='estateApp.estate')),
            ],
        ),
        migrations.CreateModel(
            name='EstateFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_plan_image', models.ImageField(upload_to='floor_plans/')),
                ('plan_title', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='estateApp.estate')),
                ('plot_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='estateApp.plotsize')),
            ],
            options={
                'ordering': ['-date_uploaded'],
                'unique_together': {('estate', 'plot_size')},
            },
        ),
        migrations.CreateModel(
            name='EstatePrototype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prototype_image', models.ImageField(upload_to='prototypes/')),
                ('Title', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to='estateApp.estate')),
                ('plot_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prototypes', to='estateApp.plotsize')),
            ],
            options={
                'ordering': ['-date_uploaded'],
                'unique_together': {('estate', 'plot_size')},
            },
        ),
    ]
