# Generated by Django 5.1.4 on 2025-02-20 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0010_estateamenitie_estatefloorplan_estateprototype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estatefloorplan',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='estateprototype',
            unique_together=set(),
        ),
    ]
