# Generated by Django 5.1.4 on 2025-02-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0011_alter_estatefloorplan_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_image', models.ImageField(upload_to='estate_layouts/', verbose_name='Estate Layout Image')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estate_layout', to='estateApp.estate')),
            ],
            options={
                'verbose_name': 'Estate Layout',
                'verbose_name_plural': 'Estate Layouts',
            },
        ),
    ]
