# Generated by Django 5.1.4 on 2025-02-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0012_estatelayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstateMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('google_map_link', models.URLField(blank=True, max_length=100000, null=True, verbose_name='Google Maps Link')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='estateApp.estate')),
            ],
            options={
                'verbose_name': 'Estate Map',
                'verbose_name_plural': 'Estate Maps',
            },
        ),
    ]
