# Generated by Django 5.1.4 on 2025-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0015_propertyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='Attachment'),
        ),
    ]
