# Generated by Django 5.1.4 on 2025-02-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0017_message_deleted_message_edited_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_replied',
        ),
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reply',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='estateApp.message', verbose_name='Reply To'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10, verbose_name='Message Status'),
        ),
    ]
