# Generated by Django 5.1.4 on 2025-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0018_remove_message_date_replied_remove_message_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ANNOUNCEMENT', 'General Announcement'), ('CLIENT_ANNOUNCEMENT', 'Client Announcement'), ('MARKETER_ANNOUNCEMENT', 'Marketer Announcement')], default='ANNOUNCEMENT', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
