# Generated by Django 5.1.4 on 2025-06-04 11:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0020_usernotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandPlotTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('installment', 'Installment Plan')], max_length=20)),
                ('installment_plan', models.CharField(blank=True, choices=[('50-30-20', '50% - 30% - 20% (Standard)'), ('60-20-20', '60% - 20% - 20%'), ('40-30-30', '40% - 30% - 30%'), ('custom', 'Custom Plan')], max_length=20, null=True)),
                ('custom_plan', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_duration', models.IntegerField(blank=True, choices=[(3, '3 Months'), (6, '6 Months'), (12, '12 Months'), ('custom', 'Custom')], null=True)),
                ('custom_duration', models.IntegerField(blank=True, null=True)),
                ('first_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('second_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('third_installment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('status', models.CharField(choices=[('Fully Paid', 'Fully Paid'), ('Part Payment', 'Part Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to=settings.AUTH_USER_MODEL)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.estate')),
                ('marketer', models.ForeignKey(limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.CASCADE, related_name='marketer_transactions', to=settings.AUTH_USER_MODEL)),
                ('plot_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.plotsize')),
            ],
            options={
                'verbose_name': 'Land Plot Transaction',
                'verbose_name_plural': 'Land Plot Transactions',
                'ordering': ['-transaction_date'],
            },
        ),
    ]
