# Generated by Django 5.1.4 on 2025-06-04 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0021_landplottransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landplottransaction',
            options={},
        ),
    ]
