# Generated by Django 5.1.4 on 2025-06-08 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0022_alter_landplottransaction_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('special_notes', models.TextField(blank=True, null=True)),
                ('first_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('second_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('third_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_duration', models.PositiveSmallIntegerField(blank=True, help_text="Only used if allocation.payment_type == 'part'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allocation', models.ForeignKey(help_text='Pre-existing allocation ties together client, estate, plot size & payment type.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='estateApp.plotallocation')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('marketer', models.ForeignKey(editable=False, limit_choices_to={'role': 'marketer'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Land Plot Transaction',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='LandPlotTransaction',
        ),
    ]
