# Generated by Django 5.1.4 on 2025-06-09 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0023_transaction_delete_landplottransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='assigned_marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='estateApp.marketeruser', verbose_name='Assigned Marketer'),
        ),
        migrations.AlterField(
            model_name='plotallocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.clientuser', verbose_name='Registered Client Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='estateApp.plotallocation'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='estateApp.clientuser'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='marketer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='estateApp.marketeruser'),
        ),
    ]
