# Generated by Django 5.1.4 on 2025-06-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0024_clientuser_assigned_marketer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='marketer',
        ),
    ]
