# Generated by Django 5.1.4 on 2025-06-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0025_remove_customuser_marketer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_duration',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Custom duration in months', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='first_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='installment_plan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='second_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='third_installment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
