# Generated by Django 5.1.4 on 2025-06-11 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0026_transaction_custom_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment', models.IntegerField(choices=[(1, 'First Installment'), (2, 'Second Installment'), (3, 'Third Installment')])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=20)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('pos', 'POS')], max_length=10)),
                ('reference_note', models.CharField(blank=True, max_length=255, null=True)),
                ('send_receipt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.transaction')),
            ],
        ),
    ]
