# Generated by Django 5.1.4 on 2025-06-12 01:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0027_paymentrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'ordering': ('transaction', 'installment')},
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='installment',
            field=models.PositiveSmallIntegerField(choices=[(1, 'First Installment'), (2, 'Second Installment'), (3, 'Third Installment')]),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='estateApp.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together={('transaction', 'installment')},
        ),
    ]
