# Generated by Django 5.1.4 on 2025-06-12 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0028_alter_paymentrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={},
        ),
    ]
