# Generated by Django 5.1.4 on 2025-06-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0029_alter_paymentrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='custom_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='installment_plan',
            field=models.CharField(blank=True, choices=[('50-30-20', '50-30-20'), ('60-20-20', '60-20-20'), ('40-30-30', '40-30-30'), ('custom', 'Custom')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
