# Generated by Django 5.1.4 on 2025-06-17 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0030_alter_transaction_custom_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('pos', 'POS')], help_text='Only for full payments', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_code',
            field=models.CharField(max_length=50, null=True, editable=False),
        ),
    ]
