# Generated by Django 5.1.4 on 2025-06-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0031_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_code',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
