# Generated by Django 5.1.4 on 2025-06-18 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0032_alter_transaction_reference_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='reference_code',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='installment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estateApp.marketeruser'),
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='reference_note',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='send_receipt',
        ),
    ]
