# Generated by Django 5.1.4 on 2025-06-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0033_alter_paymentrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction_date']},
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='selected_installment',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], help_text='The installment the client selected when making payment', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('pos', 'POS')], max_length=10, null=True),
        ),
    ]
