# Generated by Django 5.1.4 on 2025-06-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0034_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='receipt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='receipt_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
