# Generated by Django 5.1.4 on 2025-06-20 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0035_paymentrecord_receipt_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Commission Percentage')),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='estateApp.marketeruser')),
            ],
            options={
                'verbose_name': 'Commission Rate',
                'verbose_name_plural': 'Commission Rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10)),
                ('period_identifier', models.CharField(max_length=20)),
                ('closed_deals', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='estateApp.marketeruser')),
            ],
            options={
                'verbose_name': 'Marketer Performance',
                'verbose_name_plural': 'Marketer Performances',
                'unique_together': {('marketer', 'period_type', 'period_identifier')},
            },
        ),
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10)),
                ('period_identifier', models.CharField(max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to='estateApp.marketeruser')),
            ],
            options={
                'verbose_name': 'Sales Target',
                'verbose_name_plural': 'Sales Targets',
                'unique_together': {('marketer', 'period_type', 'period_identifier')},
            },
        ),
    ]
