# Generated by Django 5.1.4 on 2025-06-20 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0036_commissionrate_marketerperformance_salestarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('plots', models.PositiveIntegerField(default=1)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='estateApp.clientuser')),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_transactions', to='estateApp.marketeruser')),
            ],
        ),
    ]
