# Generated by Django 5.1.4 on 2025-06-22 14:23

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0037_clienttransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketerCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apply_to_all', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MarketerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_via_email', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_app', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketerTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('specific_period', models.CharField(max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notify_marketer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='clienttransaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clienttransaction',
            name='marketer',
        ),
        migrations.RemoveField(
            model_name='commissionrate',
            name='marketer',
        ),
        migrations.AlterUniqueTogether(
            name='salestarget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salestarget',
            name='marketer',
        ),
        migrations.AlterModelOptions(
            name='marketerperformance',
            options={},
        ),
        migrations.RenameField(
            model_name='marketerperformance',
            old_name='period_identifier',
            new_name='specific_period',
        ),
        migrations.RenameField(
            model_name='marketerperformance',
            old_name='timestamp',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='marketerperformance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketerperformance',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='marketerperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketerperformance',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='marketerperformance',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='estateApp.marketeruser'),
        ),
        migrations.AlterField(
            model_name='marketerperformance',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='marketerperformance',
            unique_together={('marketer', 'period_type', 'specific_period')},
        ),
        migrations.AddIndex(
            model_name='marketerperformance',
            index=models.Index(fields=['period_type', 'specific_period'], name='estateApp_m_period__61b837_idx'),
        ),
        migrations.AddIndex(
            model_name='marketerperformance',
            index=models.Index(fields=['marketer'], name='estateApp_m_markete_b44264_idx'),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commissions', to='estateApp.marketeruser'),
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='estateApp.marketeruser'),
        ),
        migrations.AddField(
            model_name='marketermessage',
            name='marketer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='estateApp.marketeruser'),
        ),
        migrations.AddField(
            model_name='marketermessage',
            name='sent_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketer_messages_sent', to='estateApp.marketeruser'),
        ),
        migrations.AddField(
            model_name='marketertarget',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to='estateApp.marketeruser'),
        ),
        migrations.AddField(
            model_name='marketertarget',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='estateApp.marketeruser', verbose_name='Marketer'),
        ),
        migrations.DeleteModel(
            name='ClientTransaction',
        ),
        migrations.DeleteModel(
            name='CommissionRate',
        ),
        migrations.DeleteModel(
            name='SalesTarget',
        ),
        migrations.AlterUniqueTogether(
            name='marketercommission',
            unique_together={('marketer', 'effective_date')},
        ),
        migrations.AlterUniqueTogether(
            name='marketertarget',
            unique_together={('marketer', 'period_type', 'specific_period')},
        ),
    ]
