# Generated by Django 5.1.4 on 2025-06-29 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0038_marketercommission_marketermessage_marketertarget_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketerperformance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='marketerperformance',
            name='marketer',
        ),
        migrations.AlterModelOptions(
            name='marketercommission',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Commission Rate', 'verbose_name_plural': 'Commission Rates'},
        ),
        migrations.AlterModelOptions(
            name='marketertarget',
            options={'verbose_name': 'Sales Target', 'verbose_name_plural': 'Sales Targets'},
        ),
        migrations.AlterUniqueTogether(
            name='marketercommission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='marketertarget',
            unique_together={('period_type', 'specific_period', 'marketer')},
        ),
        migrations.AddField(
            model_name='marketercommission',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Commission Rate (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marketercommission',
            name='effective_date',
            field=models.DateField(verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='marketercommission',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estateApp.marketeruser', verbose_name='Marketer (leave blank for all marketers)'),
        ),
        migrations.AlterField(
            model_name='marketertarget',
            name='marketer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estateApp.marketeruser', verbose_name='Marketer (leave blank for all marketers)'),
        ),
        migrations.AlterField(
            model_name='marketertarget',
            name='period_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20, verbose_name='Period Type'),
        ),
        migrations.AlterField(
            model_name='marketertarget',
            name='specific_period',
            field=models.CharField(max_length=20, verbose_name='Specific Period (e.g., 2024-04, 2024-Q2, 2024)'),
        ),
        migrations.AlterField(
            model_name='marketertarget',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Target Amount (₦)'),
        ),
        migrations.CreateModel(
            name='MarketerPerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('specific_period', models.CharField(max_length=20)),
                ('closed_deals', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.marketeruser')),
            ],
            options={
                'unique_together': {('marketer', 'period_type', 'specific_period')},
            },
        ),
        migrations.DeleteModel(
            name='MarketerMessage',
        ),
        migrations.DeleteModel(
            name='MarketerPerformance',
        ),
        migrations.RemoveField(
            model_name='marketercommission',
            name='apply_to_all',
        ),
        migrations.RemoveField(
            model_name='marketercommission',
            name='commission_rate',
        ),
        migrations.RemoveField(
            model_name='marketercommission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='marketertarget',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='marketertarget',
            name='notify_marketer',
        ),
    ]
