# Generated by Django 5.1.4 on 2025-07-12 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0039_alter_marketerperformance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount', models.PositiveSmallIntegerField(help_text='Percentage discount (1–100)')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('description', models.TextField(blank=True, help_text='Optional promo description/details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estates', models.ManyToManyField(help_text='Estates this promo applies to', related_name='promotional_offers', to='estateApp.estate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presale', models.DecimalField(decimal_places=2, help_text='Initial presale price', max_digits=12)),
                ('previous', models.DecimalField(decimal_places=2, help_text='Previous price before this change', max_digits=12)),
                ('current', models.DecimalField(decimal_places=2, help_text='Current active price', max_digits=12)),
                ('effective', models.DateField(help_text='Date this price becomes effective')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this price change')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='estateApp.estate')),
                ('plot_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_prices', to='estateApp.plotsizeunits')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('estate', 'plot_unit')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='estateApp.propertyprice')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
