# Generated by Django 5.1.4 on 2025-08-09 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0040_promotionaloffer_propertyprice_pricehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=50)),
                ('birthday_opt_in', models.BooleanField(default=True)),
                ('preferred_channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=20)),
                ('send_time_local', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Preference',
                'verbose_name_plural': 'Birthday Preferences',
            },
        ),
        migrations.CreateModel(
            name='BirthdayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('audience', models.CharField(choices=[('client', 'Clients'), ('marketer', 'Marketers'), ('both', 'Both')], default='client', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField(help_text='Use placeholders like {{ first_name }}, {{ full_name }}, {{ coupon_code }}')),
                ('is_active', models.BooleanField(default=True)),
                ('send_time_local', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Birthday Template',
                'verbose_name_plural': 'Birthday Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BirthdayLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('action', models.CharField(default='auto', max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birthday_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estateApp.birthdaytemplate')),
            ],
            options={
                'verbose_name': 'Birthday Log',
                'verbose_name_plural': 'Birthday Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
