# Generated by Django 5.1.4 on 2025-08-09 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0041_birthdaypreference_birthdaytemplate_birthdaylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaytemplate',
            name='body',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='BulkMessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('total_sent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Message Campaign',
                'verbose_name_plural': 'Bulk Message Campaigns',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=300, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='estateApp.bulkmessagecampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Message Log',
                'verbose_name_plural': 'Bulk Message Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('holiday', 'Holiday'), ('promotion', 'Promotion'), ('announcement', 'Announcement'), ('other', 'Other')], default='holiday', max_length=20)),
                ('audience', models.CharField(choices=[('client', 'Clients'), ('marketer', 'Marketers'), ('both', 'Both')], default='client', max_length=20)),
                ('channels', models.CharField(default='in_app', max_length=100)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Message Template',
                'verbose_name_plural': 'Bulk Message Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkmessagecampaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estateApp.bulkmessagetemplate'),
        ),
    ]
