# Generated by Django 5.1.4 on 2025-08-11 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0042_alter_birthdaytemplate_body_bulkmessagecampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Support User',
                'verbose_name_plural': 'Support Users',
            },
            bases=('estateApp.customuser',),
        ),
        migrations.RemoveField(
            model_name='birthdaypreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='birthdaytemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bulkmessagecampaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bulkmessagecampaign',
            name='template',
        ),
        migrations.RemoveField(
            model_name='bulkmessagelog',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='bulkmessagelog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bulkmessagetemplate',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('client', 'Client'), ('marketer', 'Marketer'), ('support', 'Support')], max_length=20, null=True, verbose_name='Role'),
        ),
        migrations.DeleteModel(
            name='BirthdayLog',
        ),
        migrations.DeleteModel(
            name='BirthdayPreference',
        ),
        migrations.DeleteModel(
            name='BirthdayTemplate',
        ),
        migrations.DeleteModel(
            name='BulkMessageCampaign',
        ),
        migrations.DeleteModel(
            name='BulkMessageLog',
        ),
        migrations.DeleteModel(
            name='BulkMessageTemplate',
        ),
    ]
