# Generated by Django 5.1.4 on 2025-10-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0043_supportuser_remove_birthdaypreference_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Deletion Reason'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
