# Generated by Django 5.1.4 on 2025-10-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0044_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='title_deed',
            field=models.CharField(choices=[('FCDA RofO', 'FCDA RofO'), ('FCDA CofO', 'FCDA CofO'), ('RofO', 'RofO'), ('Gazette', 'Gazette')], max_length=255, verbose_name='Title Deed'),
        ),
    ]
