# Generated by Django 5.1.4 on 2025-10-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0045_alter_estate_title_deed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True, verbose_name='Company Name')),
                ('registration_number', models.CharField(max_length=100, unique=True, verbose_name='Registration Number')),
                ('registration_date', models.DateField(verbose_name='Company Registration Date')),
                ('location', models.CharField(max_length=255, verbose_name='Company Location')),
                ('ceo_name', models.CharField(max_length=255, verbose_name='CEO Name')),
                ('ceo_dob', models.DateField(verbose_name='CEO Date of Birth')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Company Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Company Phone')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Company Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='estateApp.company', verbose_name='Company'),
        ),
    ]
