# Generated by Django 5.1.4 on 2025-10-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0046_company_customuser_company_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Last Login IP'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Login Location'),
        ),
        migrations.CreateModel(
            name='AppMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_downloads', models.PositiveIntegerField(default=0)),
                ('ios_downloads', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_metrics', to='estateApp.company')),
            ],
            options={
                'verbose_name': 'App Metrics',
                'verbose_name_plural': 'App Metrics',
            },
        ),
    ]
