# Generated by Django 5.1.4 on 2025-10-31 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0047_customuser_last_login_ip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('device_model', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Device Token',
                'verbose_name_plural': 'User Device Tokens',
                'indexes': [models.Index(fields=['user', 'platform'], name='estateApp_u_user_id_9acf60_idx'), models.Index(fields=['is_active'], name='estateApp_u_is_acti_d66225_idx')],
            },
        ),
    ]
