# Generated by Cascade on 2025-11-05
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estateApp', '0049_notificationdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone',
            field=models.BooleanField(default=False, verbose_name='Deleted For Everyone'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted For Everyone At'),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_everyone_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name='messages_deleted_globally',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Deleted For Everyone By',
            ),
        ),
    ]
